#ifndef DEFAULTS_h
#define DEFAULT_H

#define DEFAULT_WINDOW_W 1024
#define DEFAULT_WINDOW_H 768
#define DEFAULT_OPACITY 255
#define DEFAULT_FOV 80.0

#define DEFAULT_FPS_TARGET 60
#define DEFAULT_MESH_BUFFER_SIZE 1024

#endif
